name: kartal
description: Kartal is an extension package for easy to use at app development
  time. You can access more features with primitive variables(context, string
  etc.).
version: 4.0.4
issue_tracker: https://github.com/vb10/kartal/issues
repository: https://github.com/VB10/kartal
screenshots:
  - description: 'City of Kartal, Istanbul'
    path: github/screen/kartal.jpeg

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  device_info_plus: ^10.1.2
  diacritic: ^0.1.5
  dio: ^5.6.0
  flutter:
    sdk: flutter
  html: ^0.15.4
  logger: ^2.4.0
  mask_text_input_formatter: ^2.9.0
  mime: ^1.0.5
  package_info_plus: ^8.0.2
  share_plus: ^10.0.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
